version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "82:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        container_name: laravel1_nginx
        platform: linux/amd64
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        container_name: laravel1_php
        platform: linux/amd64

    project5_mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'laravel1'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'laravel1'
        volumes:
            - project5_mysql_data:/var/lib/mysql
        ports:
            - 3311:3306
        container_name: laravel1_mysql
        platform: linux/amd64

volumes:
    project5_mysql_data: